services:
  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge